name: Trunk Analytics Uploader Wrapper
description: Wrapper that supplies defaults to the `analytics-uploader` action

inputs:
  token-staging:
    description: Organization token for staging.
    required: true
  junit-paths:
    description: Comma-separated list of glob paths to junit files.
    required: true
  bazel-bep-path:
    description: Path to the Bazel BEP file.
    required: false
  run:
    description: The command to run before uploading test results.
    required: false
  cli-version:
    description: The version of the uploader to use.
    required: false

runs:
  using: composite
  steps:
    - name: Upload test results with CLI version ${{ inputs.cli-version }} to staging
      if: "${{ inputs.cli-version != '' }}"
      continue-on-error: true
      uses: trunk-io/analytics-uploader@main
      with:
        org-slug: max-test-org
        token: ${{ inputs.token-staging }}
        cli-version: ${{ inputs.cli-version }}
        junit-paths: ${{ inputs.junit-paths }}
        bazel-bep-path: ${{ inputs.bazel-bep-path }}
        run: ${{ inputs.run }}
        quarantine: true
      env:
        TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
